version: "3.8"

services:
  app:
    build: .
    container_name: nextjs-app
    restart: always
    environment:
      NEXT_PUBLIC_API_URL:
      NEXTAUTH_SECRET:
      NEXTAUTH_URL:
    ports:
      - "3000:3000"
