version: '3.8'

services:
  app:
    build: .
    container_name: nestjs-app
    restart: always
    environment:
      NODE_ENV: 
      PORT: 
      DATABASE_HOST: 
      DATABASE_PORT: 
      DATABASE_USERNAME: 
      DATABASE_PASSWORD: 
      DATABASE_NAME: 
      DATABASE_URL: 
      JWT_SECRET: 
    ports:
      - 
    depends_on:
      - db
    command: >
      sh -c "
      npx prisma migrate deploy &&
      node dist/main
      "

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
